"""Rename password to password_hash

Revision ID: 0fc5eb980125
Revises: 71726c62413d
Create Date: 2025-01-30 10:47:15.224161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fc5eb980125'
down_revision: Union[str, None] = '71726c62413d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.drop_column('users', 'password')
    op.drop_column('users', 'number')
    op.drop_constraint('votes_post_id_fkey', 'votes', type_='foreignkey')
    op.drop_constraint('votes_user_id_fkey', 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key('votes_user_id_fkey', 'votes', 'users', ['user_id'], ['id'])
    op.create_foreign_key('votes_post_id_fkey', 'votes', 'posts', ['post_id'], ['id'])
    op.add_column('users', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
