"""empty message

Revision ID: a5b94caf64b7
Revises: e6e1dca39b3a
Create Date: 2025-01-28 16:16:14.674791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5b94caf64b7'
down_revision: Union[str, None] = 'e6e1dca39b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('votes', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('votes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('unique_post_user', 'votes', type_='unique')
    op.create_index(op.f('ix_votes_id'), 'votes', ['id'], unique=False)
    op.drop_constraint('votes_users_fkey', 'votes', type_='foreignkey')
    op.drop_constraint('votes_posts_fkey', 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'votes', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key('votes_posts_fkey', 'votes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('votes_users_fkey', 'votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_votes_id'), table_name='votes')
    op.create_unique_constraint('unique_post_user', 'votes', ['post_id', 'user_id'])
    op.alter_column('votes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('votes', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
